#!/bin/sh 

alias config='/usr/bin/git --git-dir=/home/cliford/.local/share/cfg/ --work-tree=/home/cliford'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkdir="mkdir -pv"

# Colorize commands when possible.
alias \
	ls="ls -FhN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

alias mntwin="sudo mount /dev/nvme0n1p3 /media/windows"

alias rm="echo \"Don't you mean trash-put?\"; false"

alias tp="trash-put"
