#!/bin/bash

setxkbmap -option caps:escape  

# caps lock on shift+esc
xmodmap -e "keycode 9 = Escape Caps_Lock"

# remap Insert to Super and shift+key for original functionality
 xmodmap -e "keycode 118 = Super_R Insert" 
