#!/bin/bash

xrdb -merge /home/cliford/.Xresources

xrandr --auto
xrandr --output HDMI-A-0 --scale 1.25x1.25 --left-of eDP
xrandr --output DisplayPort-0 --scale 1.25x1.25 --left-of eDP
xrandr --output eDP --scale 0.9999x0.9999 --pos 2400x270 --primary

#xrandr --output HDMI-1 --scale 1.25x1.25 --left-of eDP-1 --output eDP-1 --scale 0.9999x0.9999 --output eDP-1 --pos 2400x270

## --pos flag with the width of other display when other display is on the left
